name: monero
services:
  monerod:
    image: ghcr.io/sethforprivacy/simple-monerod:latest
    restart: unless-stopped
    container_name: monerod
    volumes:
      - bitmonero:/home/monero/.bitmonero
    ports:
      - 18080:18080
      - 18084:18084
      - 18089:18089
    depends_on:
      tor:
        condition: service_started
    healthcheck:
      test: curl --fail http://localhost:18081/get_height || exit 1
      interval: 60s
      timeout: 5s
      retries: 10
      start_period: 40s
    networks:
      monero_suite_net:
        ipv4_address: 172.28.1.3
    command:
      - --rpc-restricted-bind-ip=0.0.0.0
      - --rpc-restricted-bind-port=18089
      - --rpc-bind-ip=0.0.0.0
      - --rpc-bind-port=18081
      - --confirm-external-bind
      - --check-updates=disabled
      - --enable-dns-blocklist
      - --log-level=0
      - --max-log-file-size=1048576
      - --max-log-files=3
      - --no-igd
      - --p2p-bind-port=18080
      - --out-peers=32
      - --in-peers=48
      - --limit-rate-up=1048576
      - --limit-rate-down=1048576
      - --allow-local-ip
      - --public-node
      - --db-sync-mode=fast:async:250000000bytes
      - --max-txpool-weight=2684354560
      - --fast-block-sync=1
      - --zmq-pub=tcp://0.0.0.0:18084
      - --restricted-rpc
      - --tx-proxy=tor,172.28.1.2:9050,32
      - --add-priority-node=xwvz3ekocr3dkyxfkmgm2hvbpzx2ysqmaxgter7znnqrhoicygkfswid.onion:18083
      - --add-priority-node=4pixvbejrvihnkxmduo2agsnmc3rrulrqc7s3cbwwrep6h6hrzsibeqd.onion:18083
      - --add-priority-node=zbjkbsxc5munw3qusl7j2hpcmikhqocdf4pqhnhtpzw5nt5jrmofptid.onion:18083
      - --add-priority-node=plowsof3t5hogddwabaeiyrno25efmzfxyro2vligremt7sxpsclfaid.onion:18083
      - --add-priority-node=plowsoffjexmxalw73tkjmf422gq6575fc7vicuu4javzn2ynnte6tyd.onion:18083
      - --add-priority-node=qz43zul2x56jexzoqgkx2trzwcfnr6l3hbtfcfx54g4r3eahy3bssjyd.onion:18083
      - --add-peer=xwvz3ekocr3dkyxfkmgm2hvbpzx2ysqmaxgter7znnqrhoicygkfswid.onion:18083
      - --add-peer=4pixvbejrvihnkxmduo2agsnmc3rrulrqc7s3cbwwrep6h6hrzsibeqd.onion:18083
      - --add-peer=zbjkbsxc5munw3qusl7j2hpcmikhqocdf4pqhnhtpzw5nt5jrmofptid.onion:18083
      - --add-peer=plowsof3t5hogddwabaeiyrno25efmzfxyro2vligremt7sxpsclfaid.onion:18083
      - --add-peer=plowsoffjexmxalw73tkjmf422gq6575fc7vicuu4javzn2ynnte6tyd.onion:18083
      - --add-peer=qz43zul2x56jexzoqgkx2trzwcfnr6l3hbtfcfx54g4r3eahy3bssjyd.onion:18083
  p2pool-mini:
    image: ghcr.io/sethforprivacy/p2pool:latest
    restart: unless-stopped
    container_name: p2pool-mini
    tty: true
    stdin_open: true
    volumes:
      - p2pool-data:/home/p2pool
      - /dev/null:/home/p2pool/.p2pool/p2pool.log:rw
      - /dev/hugepages:/dev/hugepages:rw
    ports:
      - 3333:3333
      - 37888:37888
    networks:
      monero_suite_net:
        ipv4_address: 172.28.1.5
        aliases:
          - p2pool-mini
    depends_on:
      monerod:
        condition: service_healthy
    command: --wallet
      43CY9S5WVDN3pNLDWTid73Kv3Lu1zQNS7ULZdunvjKVXYXhQ7RSQ1DDJDq24ChmqX3e33bWpiGHVuBB4AyNW4bebLxZ5Qo2
      --stratum 0.0.0.0:3333 --p2p 0.0.0.0:37888 --rpc-port 18089 --zmq-port
      18084 --host 172.28.1.3 --no-dns --mini
  tor:
    image: ghcr.io/hundehausen/tor-hidden-service:latest
    container_name: tor
    restart: unless-stopped
    networks:
      monero_suite_net:
        ipv4_address: 172.28.1.2
        aliases:
          - tor
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    environment:
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_POLL_INTERVAL: 3600
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  autoheal:
    image: willfarrell/autoheal:latest
    container_name: autoheal
    restart: unless-stopped
    environment:
      AUTOHEAL_CONTAINER_LABEL: all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  xmrig:
    image: metal3d/xmrig:latest
    container_name: xmrig
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
      - SYS_RAWIO
    volumes:
      - /lib/modules:/lib/modules
    environment:
      POOL_URL: p2pool-mini:3333
      POOL_USER: xmrig
      POOL_PASS: ""
      DONATE_LEVEL: 1
volumes:
  bitmonero: {}
  p2pool-data: {}
networks:
  monero_suite_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.1.0/24
