global:
  evaluation_interval: 10m
scrape_configs:
  - job_name: "node-exporter"
    scrape_interval: 20s
    scrape_timeout: 20s
    static_configs:
      - targets: ["exporter:9000"]
  - job_name: "nodemapper"
    scrape_interval: 2m
    scrape_timeout: 1m
    static_configs:
      - targets: ["nodemapper:5000"]
