name: Publish Prometheus to Docker Hub

on: workflow_dispatch

env:
  DH_USER: bcath

jobs:
  prometheus:
    name: Publish prometheus image
    runs-on: ubuntu-24.04
    steps:
      - name: Authenticate to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push prometheus image
        run: bash release.sh prometheus ${{ env.DH_USER }}
